### ISSUE TITLE
다변수 β reduction

### ISSUE THREAD

**Issue by baehyunsol** [Zeta611/lamb#1]
`(\x.\y.x)`는 변수 2개를 받아서 앞에 거를 반환하고 `(\x.\y.y)`는 변수 2개를 받아서 뒤에 거를 반환하는 거라고 생각했는데 아래의 코드를 돌려보니 출력이 예상과 다릅니다.

```rust
use lamb::*;

fn main() {
    let val1 = beta_red(parse("(\\x.\\y.x) x y"), 0);
    println!("{val1:?}");
    let val2 = beta_red(parse("(\\x.\\y.y) x y"), 0);
    println!("{val2:?}");
}
```

출력

```rust
(Lamb("$0", App(Var("x"), Var("y"))), 1)
(Lamb("$0", Var("$0")), 1)
```

변수 여러 개를 입력하는 문법이 따로 있나요?

**Comment by Zeta611** [comment]
Associativity 때문에 생기는 문제인데요, 일단은 `((\\x.\\y.x) x) y`로 감싸주면 됩니다. 왜 이런지 확인해보겠습니다.

**Comment by Zeta611** [comment]
Fixed by [110b9df](https://github.com/Zeta611/lamb/commit/110b9df451a50ffbf986af0fe89801851ccabce9)
